"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { motion } from "framer-motion";
import { CheckCircle, XCircle, ExternalLink, Shield, Code } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Accordion } from "@/components/ui/accordion";
import { decodeAttestation, ShareableAttestation } from "@/lib/utils";

const ATTRIBUTE_LABELS: Record<string, string> = {
  name: "Full Name",
  dateOfBirth: "Date of Birth",
  ageOver21: "Age Over 21",
  notExpired: "Document Not Expired",
  nationality: "Nationality",
  documentType: "Document Type",
};

export default function RelyingPartyView() {
  const params = useParams();
  const [attestation, setAttestation] = useState<ShareableAttestation | null>(null);
  const [isValid, setIsValid] = useState<boolean | null>(null);

  useEffect(() => {
    const attestationId = params.attestationId as string;
    if (!attestationId) {
      setIsValid(false);
      return;
    }

    const decoded = decodeAttestation(attestationId);
    if (decoded) {
      setAttestation(decoded);
      setIsValid(true);
    } else {
      setIsValid(false);
    }
  }, [params.attestationId]);

  if (isValid === null) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="animate-pulse text-muted-foreground">
          Verifying attestation...
        </div>
      </div>
    );
  }

  const attributeLabel = attestation
    ? ATTRIBUTE_LABELS[attestation.attribute] || attestation.attribute
    : "";
  const displayValue =
    attestation?.value === true
      ? "Verified ✓"
      : attestation?.value === false
      ? "Not Verified"
      : String(attestation?.value || "");

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-6 py-12">
        <header className="text-center mb-10">
          <h1 className="text-3xl font-bold text-primary mb-2">Dokimos</h1>
          <p className="text-muted-foreground">Identity Attestation</p>
        </header>

        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="text-center mb-8"
        >
          {isValid && attestation ? (
            <div className="space-y-6">
              <div className="w-24 h-24 mx-auto rounded-full bg-green-100 flex items-center justify-center">
                <CheckCircle className="w-12 h-12 text-green-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-green-800">Verified</h2>
                <p className="text-muted-foreground mt-1">
                  This attestation is cryptographically valid
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="w-24 h-24 mx-auto rounded-full bg-red-100 flex items-center justify-center">
                <XCircle className="w-12 h-12 text-red-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-red-800">Could Not Verify</h2>
                <p className="text-muted-foreground mt-1">
                  This attestation could not be validated
                </p>
              </div>
            </div>
          )}
        </motion.div>

        {isValid && attestation && (
          <>
            <Card className="mb-6">
              <CardContent className="p-6 text-center">
                <p className="text-sm text-muted-foreground mb-1">
                  {attributeLabel}
                </p>
                <p className="text-3xl font-bold text-foreground">{displayValue}</p>
                <p className="text-sm text-muted-foreground mt-4">
                  Verified on {new Date(attestation.timestamp).toLocaleString()}
                </p>
              </CardContent>
            </Card>

            <Accordion title="How is this verified?" className="mb-6">
              <div className="space-y-4 text-sm text-muted-foreground">
                <div className="flex items-start gap-3">
                  <Shield className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                  <p>
                    This attestation was generated by code running inside an{" "}
                    <strong className="text-foreground">
                      Intel TDX Trusted Execution Environment
                    </strong>
                    . The signature was produced by a wallet that only that specific,
                    auditable code can access.
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <Code className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                  <p>
                    You can verify this yourself: the signer address below is tied to
                    a specific Docker image hash on EigenCloud. View the source code
                    and confirm it does exactly what it claims.
                  </p>
                </div>
              </div>
            </Accordion>

            <div className="flex flex-col sm:flex-row gap-3 mb-8">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => window.open("https://etherscan.io/verifySig", "_blank")}
              >
                <ExternalLink className="w-4 h-4 mr-2" />
                Verify Signature on Etherscan
              </Button>
              <Button
                variant="outline"
                className="flex-1"
                onClick={() =>
                  window.open("https://verifiability.eigencloud.xyz", "_blank")
                }
              >
                <ExternalLink className="w-4 h-4 mr-2" />
                View Code on EigenCloud
              </Button>
            </div>

            <Card>
              <CardContent className="p-6">
                <h4 className="text-sm font-semibold mb-4">Raw Attestation Data</h4>
                <div className="bg-gray-900 text-gray-100 rounded-lg p-4 font-mono text-xs overflow-x-auto">
                  <div className="space-y-2">
                    <div>
                      <span className="text-gray-400">message:</span>{" "}
                      <span className="text-green-400 break-all">
                        {attestation.message}
                      </span>
                    </div>
                    <div>
                      <span className="text-gray-400">messageHash:</span>{" "}
                      <span className="text-blue-400 break-all">
                        {attestation.messageHash}
                      </span>
                    </div>
                    <div>
                      <span className="text-gray-400">signature:</span>{" "}
                      <span className="text-purple-400 break-all">
                        {attestation.signature}
                      </span>
                    </div>
                    <div>
                      <span className="text-gray-400">signer:</span>{" "}
                      <span className="text-yellow-400">{attestation.signer}</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </>
        )}
      </div>
    </div>
  );
}
